### ISSUE TITLE
[question] Time based scheduling

### ISSUE THREAD

**Issue by bobymicroby** [jfischoff/hasql-queue#106]
Guys, you knows the ins and outs of that thing.

Can it be used for time based scheduling  ?

dequeue --> not yet --> ??? --> wait 
      ↖  ------------------------    ↙

**Comment by jfischoff** [comment]
I don't think so. 

For time based scheduling I would do some where the dequeuers have a time they should check back for the next item. They would also receive a notification if a newer item is added.

So I would not use this package I would make a related one if it was up to me. 

Alternatively look at the `odd-jobs` package.

**Comment by bobymicroby** [comment]
Cool ! I will check it out. Thanks a lot man !
